### ISSUE TITLE
Add Configurable Pricing

### ISSUE THREAD

**Issue by bupp925** [SearchSpring/magento2-searchspring-feed#3]
Configurable items should contain a multi-valued field of all applicable price points from the children. I do see the "addChildAttributesToRecord" function being used for Configurable items, but I don't think the child attributes are actually getting attached.

The following example product has a different price for the XXL and 3XL sizes, but only 24.95 exists in the feed - 26.95 and 27.95 are missing: https://staging.medalsofamerica.com/brass-addict-t-shirt

We would need all possible prices in the feed should we ever need to display a Low-High price range for these Configurable items.

**Comment by julesbravo** [comment]
This is included as an option
