### ISSUE TITLE
Verify "child_name", "child_sku"

### ISSUE THREAD

**Issue by bupp925** [SearchSpring/magento2-searchspring-feed#4]
Even though you're written the code for it, "child_name" and "child_sku" does not exist in the M2 generated feed. You will find these fields missing from medalsofamerica.com, rubies.com, and kraftmusic.com:

https://github.com/SearchSpring/magento2-searchspring-feed/blob/master/Helper/Generator.php#L284

**Comment by julesbravo** [comment]
This bug was fixed
