### ISSUE TITLE
Add hierarchy_facet, respecting "Include in Navigation Menu"

### ISSUE THREAD

**Issue by bupp925** [searchspring/magento2-searchspring-feed#5]
When editing a Category in Magento, there's a setting for "Include in Navigation Menu?", with an option of yes or no. The Categories marked as No are NOT Hidden categories, but they just don't show up in the Menu - they're still active.

The existing "hierarchy" data field should remain as-is. But, a second "hierarchy_facet" field should be added, which only includes the Categories which are active for the Navigation Menu.

We've had numerous requests about setting up Field Filters to hide certain options from our Category Facet - the request is always about having us match the Categories shown in the Menu.

Note: With this in mind, the backgroundFilter of the integration would be a bit unique, using a context attribute to determine if the current category is active in the menu:

- If yes, use both "hierarchy" and "hierarchy_facet" as a backgroundFilter
- If no, only use "hierarchy" as a backgroundFilter

**Comment by julesbravo** [comment]
This is done in menu_hierarchy.
