### ISSUE TITLE
Composer.json version doesn't match latest version of magento2-searchspring-feed

### ISSUE THREAD

**Issue by willryan-stemcell** [SearchSpring/magento2-searchspring-feed#69]
Latest version is v1.2.1:
https://github.com/searchspring/magento2-searchspring-feed/releases/tag/v1.2.1

composer.json version is 1.1.4:
https://github.com/searchspring/magento2-searchspring-feed/blob/master/composer.json
`    "version": "1.1.4",`

**Comment by willryan-stemcell** [comment]
@maheshganjalagunte This issue persists in v1.2.2

**Comment by maheshganjalagunte** [comment]
@willryan-stemcell - Are you referring to the module version to composer version? I was referring to the code changes to resolve PHP compatibility

**Comment by willryan-stemcell** [comment]
@maheshganjalagunte Yes, the module version and composer version are out of sync now.

**Comment by maheshganjalagunte** [comment]
@willryan-stemcell - Thanks for the confirmation. We'll address this in the next release.

**Comment by maheshganjalagunte** [comment]
@willryan-stemcell - Just published v1.2.3 that has the matching version numbers.

**Comment by willryan-stemcell** [comment]
Fixed in https://github.com/searchspring/magento2-searchspring-feed/pull/73
